name: Epic
description: Represent larger bodies of work that span multiple user stories across multiple sprints. These epics represented as GitHub issues, labeled as epic.
title: "[EPIC] <Title of Epic>"
labels: 
  - story
body:
  - type: textarea
    id: milestone
    attributes:
      label: Milestone
      description: Link to milestone
      value: |
        Add a few sentences to describe the milestone
  - type: textarea
    id: epic
    attributes:
      label: Epic
      description: High-level overview of the Epic
      placeholder: This is a test

