name: Epic
description: Represent larger bodies of work that span multiple user stories across multiple sprints. These epics represented as GitHub issues, labeled as epic. We use these issues for the initial research and discussion before we take on the underlying user stories.
title: "[EPIC] <Title of Epic>"
labels: 
  - story
body:
  - type: textarea
    id: milestone
    attributes:
      label: Epic
      description: High-level overview of the Epic
      placeholder: This is a test

